In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('C:/Users/snkty/OneDrive/Desktop/My_Projects/Tableau/New_Orleans_AirBnB/listings.csv')

In [11]:
df.columns

Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'source', 'name',
       'description', 'neighborhood_overview', 'picture_url', 'host_id',
       'host_url', 'host_name', 'host_since', 'host_location', 'host_about',
       'host_response_time', 'host_response_rate', 'host_acceptance_rate',
       'host_is_superhost', 'host_thumbnail_url', 'host_picture_url',
       'host_neighbourhood', 'host_listings_count',
       'host_total_listings_count', 'host_verifications',
       'host_has_profile_pic', 'host_identity_verified', 'neighbourhood',
       'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 'latitude',
       'longitude', 'property_type', 'room_type', 'accommodates', 'bathrooms',
       'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price',
       'minimum_nights', 'maximum_nights', 'minimum_minimum_nights',
       'maximum_minimum_nights', 'minimum_maximum_nights',
       'maximum_maximum_nights', 'minimum_nights_avg_ntm',
       'maximum_nights_avg_ntm', 'calendar_updated', 'has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'calendar_last_scraped', 'number_of_reviews',
       'number_of_reviews_ltm', 'number_of_reviews_l30d', 'first_review',
       'last_review', 'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'license', 'instant_bookable',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month'],
      dtype='object')

In [4]:
df2 = df.filter(items = ['id',
                         'name',
                         'description',
                         'neighborhood_overview',
                         'host_name',
                         'host_since',
                         'host_location', 
                         'host_response_time', 
                         'host_acceptance_rate', 
                         'host_total_listings_count',
                         'latitude', 
                         'longitude', 
                         'property_type',
                         'room_type', 
                         'accommodates',
                         'bathrooms',
                         'bathrooms_text', 
                         'bedrooms',
                         'beds', 
                         'amenities', 
                         'price', 
                         'minimum_nights', 
                         'maximum_nights', 
                         'number_of_reviews', 
                         'review_scores_rating', 
                         'review_scores_cleanliness',
                         'review_scores_checkin',
                         'review_scores_communication', 
                         'review_scores_location', 
                         'review_scores_value'])
df2

,id,name,description,neighborhood_overview,host_name,host_since,host_location,host_response_time,host_acceptance_rate,host_total_listings_count,...,price,minimum_nights,maximum_nights,number_of_reviews,review_scores_rating,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value
0,19091,Fully Furnished Cozy Apartment,CITY OF NEW ORLEANS STR OWNER LICENSE NUMBER: ...,"NorthWest Carrollton, where this apartment is ...",John,2010-01-23,"New Orleans, LA",NaN,100%,1,...,$71.00,1,365,503,4.89,4.87,4.97,4.98,4.68,4.91
1,71624,Ravenwood Manor (Historic Bywater),You are in for a very unique stay in a neighbo...,"Ours is a neighborhood made up of artists, mus...",Susan,2011-01-29,"New Orleans, LA",within an hour,83%,3,...,$150.00,3,1125,299,4.94,4.93,4.98,4.98,4.83,4.89
2,74498,Maison Marais 1: Large Local Living,Maison Marais 1 is a stylish one-bedroom apart...,"This is a vibrant, diverse neighborhood of mos...",Georgia,2011-02-14,"New Orleans, LA",within an hour,98%,3,...,$99.00,3,1125,613,4.91,4.97,4.93,4.96,4.66,4.86
3,79536,FeelAtHomeInNewOrleans-PrivateApt,"Safe, clean & functional! Front porch and elev...","I love that it's down to earth, welcoming, his...",Miriam,2011-03-07,"New Orleans, LA",within an hour,99%,1,...,$93.00,4,28,710,4.89,4.95,4.98,4.98,4.53,4.87
4,79609,Moon Over Mazant - FIRST and FINEST in Bywater!,The Art of Hospitality,"First settled in 1806, Bywater is known for it...",Stephen,2011-03-07,"New Orleans, LA",within an hour,95%,1,...,$122.00,3,28,493,4.96,4.99,4.99,4.99,4.84,4.94
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7248,1108085930318924876,Gorgeous Uptown NOLA Suite,Enjoy a stylish experience at this centrally-l...,NaN,Fabiola,2022-10-10,"Houston, TX",NaN,NaN,2,...,$65.00,2,365,0,NaN,NaN,NaN,NaN,NaN,NaN
7249,1108090238689884268,Renovated Retreat with Heated Pool | Steps to FQ,"This single-family home, with heated pool, loc...",Our home is a 6 minute walk from the edge of t...,Charlie,2017-09-19,"Austin, TX",within an hour,99%,81,...,$459.00,1,1125,0,NaN,NaN,NaN,NaN,NaN,NaN
7250,1108873819642943328,The Bartholomew - Bywater's Best,Enjoy a stylish and peaceful experience at thi...,NaN,Kai,2014-02-26,"New Orleans, LA",NaN,NaN,4,...,$197.00,1,365,0,NaN,NaN,NaN,NaN,NaN,NaN
7251,1108995530911454316,Jazzy vibrant getaway,This vibrant retreat is perfect for groups of ...,This is a convenient location for those lookin...,New Orleans,2023-04-04,NaN,within an hour,100%,21,...,$56.00,1,365,0,NaN,NaN,NaN,NaN,NaN,NaN
7252,1109317593885640515,Beautiful Condo near French Quarter!,Located blocks from the French Quarter. This s...,"Treme, the birthplace of Jazz, is one of the o...",Dawn,2021-01-11,NaN,within an hour,99%,23,...,$137.00,1,365,0,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df2.drop_duplicates()

,id,name,description,neighborhood_overview,host_name,host_since,host_location,host_response_time,host_acceptance_rate,host_total_listings_count,...,price,minimum_nights,maximum_nights,number_of_reviews,review_scores_rating,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value
0,19091,Fully Furnished Cozy Apartment,CITY OF NEW ORLEANS STR OWNER LICENSE NUMBER: ...,"NorthWest Carrollton, where this apartment is ...",John,2010-01-23,"New Orleans, LA",NaN,100%,1,...,$71.00,1,365,503,4.89,4.87,4.97,4.98,4.68,4.91
1,71624,Ravenwood Manor (Historic Bywater),You are in for a very unique stay in a neighbo...,"Ours is a neighborhood made up of artists, mus...",Susan,2011-01-29,"New Orleans, LA",within an hour,83%,3,...,$150.00,3,1125,299,4.94,4.93,4.98,4.98,4.83,4.89
2,74498,Maison Marais 1: Large Local Living,Maison Marais 1 is a stylish one-bedroom apart...,"This is a vibrant, diverse neighborhood of mos...",Georgia,2011-02-14,"New Orleans, LA",within an hour,98%,3,...,$99.00,3,1125,613,4.91,4.97,4.93,4.96,4.66,4.86
3,79536,FeelAtHomeInNewOrleans-PrivateApt,"Safe, clean & functional! Front porch and elev...","I love that it's down to earth, welcoming, his...",Miriam,2011-03-07,"New Orleans, LA",within an hour,99%,1,...,$93.00,4,28,710,4.89,4.95,4.98,4.98,4.53,4.87
4,79609,Moon Over Mazant - FIRST and FINEST in Bywater!,The Art of Hospitality,"First settled in 1806, Bywater is known for it...",Stephen,2011-03-07,"New Orleans, LA",within an hour,95%,1,...,$122.00,3,28,493,4.96,4.99,4.99,4.99,4.84,4.94
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7248,1108085930318924876,Gorgeous Uptown NOLA Suite,Enjoy a stylish experience at this centrally-l...,NaN,Fabiola,2022-10-10,"Houston, TX",NaN,NaN,2,...,$65.00,2,365,0,NaN,NaN,NaN,NaN,NaN,NaN
7249,1108090238689884268,Renovated Retreat with Heated Pool | Steps to FQ,"This single-family home, with heated pool, loc...",Our home is a 6 minute walk from the edge of t...,Charlie,2017-09-19,"Austin, TX",within an hour,99%,81,...,$459.00,1,1125,0,NaN,NaN,NaN,NaN,NaN,NaN
7250,1108873819642943328,The Bartholomew - Bywater's Best,Enjoy a stylish and peaceful experience at thi...,NaN,Kai,2014-02-26,"New Orleans, LA",NaN,NaN,4,...,$197.00,1,365,0,NaN,NaN,NaN,NaN,NaN,NaN
7251,1108995530911454316,Jazzy vibrant getaway,This vibrant retreat is perfect for groups of ...,This is a convenient location for those lookin...,New Orleans,2023-04-04,NaN,within an hour,100%,21,...,$56.00,1,365,0,NaN,NaN,NaN,NaN,NaN,NaN
7252,1109317593885640515,Beautiful Condo near French Quarter!,Located blocks from the French Quarter. This s...,"Treme, the birthplace of Jazz, is one of the o...",Dawn,2021-01-11,NaN,within an hour,99%,23,...,$137.00,1,365,0,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df2 = df2.dropna()

In [7]:
df2

,id,name,description,neighborhood_overview,host_name,host_since,host_location,host_response_time,host_acceptance_rate,host_total_listings_count,...,price,minimum_nights,maximum_nights,number_of_reviews,review_scores_rating,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value
1,71624,Ravenwood Manor (Historic Bywater),You are in for a very unique stay in a neighbo...,"Ours is a neighborhood made up of artists, mus...",Susan,2011-01-29,"New Orleans, LA",within an hour,83%,3,...,$150.00,3,1125,299,4.94,4.93,4.98,4.98,4.83,4.89
2,74498,Maison Marais 1: Large Local Living,Maison Marais 1 is a stylish one-bedroom apart...,"This is a vibrant, diverse neighborhood of mos...",Georgia,2011-02-14,"New Orleans, LA",within an hour,98%,3,...,$99.00,3,1125,613,4.91,4.97,4.93,4.96,4.66,4.86
3,79536,FeelAtHomeInNewOrleans-PrivateApt,"Safe, clean & functional! Front porch and elev...","I love that it's down to earth, welcoming, his...",Miriam,2011-03-07,"New Orleans, LA",within an hour,99%,1,...,$93.00,4,28,710,4.89,4.95,4.98,4.98,4.53,4.87
4,79609,Moon Over Mazant - FIRST and FINEST in Bywater!,The Art of Hospitality,"First settled in 1806, Bywater is known for it...",Stephen,2011-03-07,"New Orleans, LA",within an hour,95%,1,...,$122.00,3,28,493,4.96,4.99,4.99,4.99,4.84,4.94
5,80869,"Frenchmen House ""Red Room""",Victorian-style 100+ year old house on Frenchm...,I love that my neighborhood is just far enough...,Joanne,2011-03-12,"New Orleans, LA",within an hour,99%,3,...,$80.00,1,30,923,4.82,4.77,4.93,4.91,4.71,4.83
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7110,1087032799477746223,Centrally Located 2br w/ Balcony,Experience the charm of New Orleans in our coz...,Discover the Historic Charm of New Orleans' Se...,Marigny,2017-01-23,"New Orleans, LA",within an hour,96%,230,...,$138.00,2,360,1,3.00,4.00,4.00,4.00,3.00,3.00
7118,1087845305441509231,#1414 Condo Near French Qtr/Superdome,Stunning modern condo in the heart of New Orle...,The Central Business District in New Orleans i...,Krystal,2016-08-17,"New Orleans, LA",within an hour,98%,56,...,$132.00,1,365,2,5.00,5.00,5.00,5.00,5.00,5.00
7148,1091556182079828530,Charming Oasis | Close to Uptown | Pet Friendly,Comfortable shotgun double in the heart of Upt...,Uptown/Carrollton is a laid-back residential a...,Amanda,2017-06-20,"New Orleans, LA",within an hour,100%,4,...,$96.00,2,365,2,5.00,5.00,5.00,5.00,5.00,5.00
7156,1093684821724531066,Guest suite in New Orleans,Enjoy New Orleans amongst the locals!<br /><br...,Our home is at the edge of the Faubourg/Centra...,JC And Elif,2016-02-11,"New Orleans, LA",within an hour,95%,1,...,$100.00,2,365,2,5.00,5.00,5.00,5.00,5.00,5.00
7178,1097222571265692132,"Convenient Central City Home, Near Superdome",Welcome to our charming Airbnb in Central City...,Central City in New Orleans offers a variety o...,Nessira,2011-05-08,"New York, NY",within an hour,74%,6,...,$100.00,1,365,3,5.00,5.00,5.00,5.00,5.00,5.00

In [8]:
df2.to_csv('C:/Users/snkty/OneDrive/Desktop/My_Projects/Tableau/New_Orleans_AirBnB/listings_2.csv', index = False)